spring.application.name=smartexpenseapi

# Database Configuration (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/smartexpense_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
smartexpense.app.jwtSecret=smartexpenseSecretKeyForLearningBackendDevelopment2026SmartexpenseSecretKeyForLearningBackendDevelopment2026
smartexpense.app.jwtExpirationMs=86400000

# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin