spring.application.name=smartexpenseapi

# Database Configuration (PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/smartexpense_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:srg}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
smartexpense.app.jwtSecret=${SMARTEXPENSE_JWT_SECRET:smartexpenseSecretKeyForLearningBackendDevelopment2026SmartexpenseSecretKeyForLearningBackendDevelopment2026}
smartexpense.app.jwtExpirationMs=1800000
